"""
dlt_test_3_bronze — dlt ingestion pipeline for salesforce → DuckDB.

Generated by vibedata-data-engineering scaffolding for a verified dlt source.
Use .with_resources() to select which resources to load; do not author custom
@dlt.resource wrappers — the verified source already defines all resources.

Configuration & secrets contract
--------------------------------
- Connection metadata is declared in `.dlt/config.toml` under
  `[studio.sources.dlt_test_3]` (the studio overlay) plus the
  matching `[sources.dlt_test_3.salesforce]` block that
  carries connector-native config.
- Credentials live in `.dlt/secrets.toml` under
  `[sources.dlt_test_3.salesforce.credentials]` and resolve
  through dlt's stock provider chain (env override → secrets.toml → KV provider).
- For custom field reads, use:
      dlt.secrets["sources.dlt_test_3.<field>"]
- Never read credentials from process environment or filesystem
  directly; rely on dlt's provider chain for resolution.
"""

import dlt
from salesforce import salesforce_source


def run():
    # Load the salesforce source with connection-specific credentials
    src = salesforce_source.with_args(
        section=("sources", "dlt_test_3")
    )()

    # Apply schema_contract hints to enforce freeze mode
    schema_contract = {
        "tables": "freeze",
        "columns": "freeze",
        "data_type": "freeze"
    }

    for resource_name in ["opportunity", "account", "contact", "lead"]:
        if resource_name in src.resources:
            src.resources[resource_name].apply_hints(
                schema_contract=schema_contract
            )

    # Create pipeline and run with selected resources
    pipeline = dlt.pipeline(
        pipeline_name="dlt_test_3_bronze",
        destination="duckdb",
        dataset_name="src_dlt_test_3",
    )

    load_info = pipeline.run(
        src.with_resources("opportunity", "account", "contact", "lead")
    )
    print(load_info)


if __name__ == "__main__":
    run()
