"""Tier 1 data tests for src_salesforce_1.opportunity.

Tier 1 tests validate schema integrity and are mandatory for every bronze table.
These tests run on every pipeline load to catch the most common failure modes.
"""
import pytest


def test_opportunity_dlt_id_not_null(duckdb_conn):
    """Verify _dlt_id is non-null on every row.

    _dlt_id is the deduplication key generated by dlt.
    Null values indicate a broken ingestion invariant.
    """
    result = duckdb_conn.execute(
        "SELECT COUNT(*) FROM src_salesforce_1.opportunity WHERE _dlt_id IS NULL"
    ).fetchone()[0]

    assert result == 0, f"Found {result} rows with null _dlt_id in opportunity"


def test_opportunity_dlt_id_unique(duckdb_conn):
    """Verify _dlt_id is unique across the table.

    dlt guarantees _dlt_id uniqueness within a pipeline run.
    Duplicates indicate merge write disposition failure or a dlt bug.
    """
    result = duckdb_conn.execute(
        """
        SELECT COUNT(*) FROM (
            SELECT _dlt_id, COUNT(*) as cnt
            FROM src_salesforce_1.opportunity
            GROUP BY _dlt_id
            HAVING cnt > 1
        )
        """
    ).fetchone()[0]

    assert result == 0, f"Found {result} duplicate _dlt_id values in opportunity"
